steps:
  - name: ubuntu
    args: ['ls', '-l', 'rs-parser']
  - name: rust:1.37-stretch
    args: ['cargo', 'test']
    dir: rs-parser
  - name: rust:1.37-stretch
    args: ['cargo', 'test']
    dir: java-reader
  # - name: circleci/openjdk:9-jdk
  #   entrypoint: /opt/gradle/bin/gradle
  #   args: ['test']
  #   dir: tzio-core
  #   env:
  #     - 'TERM=dumb'

tags: ['test']
