steps:
  - id: rs-parser
    waitFor: ['-']
    name: rust:1.37.0-stretch
    args: ['cargo', 'test']
    dir: rs-parser
  - id: java-reader
    waitFor: ['-']
    name: rust:1.37.0-stretch
    args: ['cargo', 'test']
    dir: java-reader
  - id: java-core
    waitFor: ['-']
    name: gradle:5.6.2-jdk11
    args: ['gradle', 'test']
    dir: tzio-core
    env:
      - 'TERM=dumb'

tags: ['test']
