# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-core:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: bash

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tzio-core/build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: gradle dependencies
          working_directory: ~/repo/tzio-core
          environment:
            TERM: dumb

      - save_cache:
          key: v1-dependencies-{{ checksum "tzio-core/build.gradle" }}
          paths:
            - ~/repo/tzio-core/.gradle

      # run tests!
      - run:
          command: gradle test
          working_directory: ~/repo/tzio-core
          environment:
            TERM: dumb

  build-rs-parser:
    docker:
      # specify the version you desire here
      - image: circleci/rust

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: cargo test
          working_directory: ~/repo/rs-parser

  build-java-reader:
    docker:
      # specify the version you desire here
      - image: circleci/rust:1.26.2-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: cargo test
          working_directory: ~/repo/java-reader

workflows:
  version: 2

  build_all:
    jobs:
      - build-core
      - build-rs-parser
      - build-java-reader
