plugins {
    alias(libs.plugins.lombok) apply false
}

ext {
    javaVersion = 17
}

allprojects {
    repositories {
        mavenCentral()
    }

    group = 'com.kineolyan'
    version = '1.2-SNAPSHOT'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.freefair.lombok'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(rootProject.javaVersion)
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        failFast = false
    }
}
