[package]
name = "parser"
version = "0.2.0"
authors = ["Kineolyan <kineolyan@protonmail.com>"]
edition = "2018"

[dependencies]
language = { path = "../language" }

[dependencies.nom]
version = "6.0.1"
features = ["alloc"]
