dependencies {
    implementation project(':tzio-spec')

    testImplementation project(':tzio-tck')
    testImplementation libs.assertj.core
    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine
    testRuntimeOnly libs.junit.platform.launcher
}

// Jar containing the core and its dependencies
def fullJar = tasks.register('fullJar', Jar) {
    manifest {
        attributes 'Implementation-Title': 'TZ Java Core (Full)',
                'Implementation-Version': project.version
    }
    archiveBaseName = project.name + '-full'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(configurations.runtimeClasspath.elements.map { files ->
        files.collect { it.asFile.isDirectory() ? it : zipTree(it) }
    })
    with jar
}
tasks.named('build') {
    dependsOn fullJar
}
